[build]
  command = "npm run docs:build"
  publish = "docs/.vuepress/dist/"

[[redirects]]
  from = "https://techtalk.ml/blog/2018-04-28-start_vupress.html"
  to = "https://blog.nakamu.life/posts/vuepress"
  status = 301


[[redirects]]
  from = "https://techtalk.ml/blog/2018-05-02-vupress_customize_layout.html"
  to = "https://blog.nakamu.life/posts/vuepress-layout-customize"
  status = 301
